
FROM  node:20-alpine  AS builder

WORKDIR /app

# Copy package files
COPY package.json package-lock.json* ./

# Install deps
RUN npm install

# Copy source
COPY . .

# Build Next.js app
RUN npm run build


# ---------- Production stage ----------
FROM node:20-alpine

WORKDIR /app

ENV NODE_ENV=production

# Copy only needed files
COPY --from=builder /app/package.json ./
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 3000

CMD ["npm", "start"]
